INSERT IGNORE INTO products (name, description, price, stock, category) VALUES
-- Electronics
('Apple iPhone 15 Pro',        'Titanium design, A17 Pro chip, 48MP camera',          54999, 20, 'Electronics'),
('Apple iPhone 15',            '6.1-inch Super Retina XDR display, USB-C',            44999, 20, 'Electronics'),
('Samsung Galaxy S24 Ultra',   '200MP camera, S Pen, Snapdragon 8 Gen 3',             59999, 20, 'Electronics'),
('Samsung Galaxy A54',         '50MP camera, 5000mAh battery, Super AMOLED',          19999, 20, 'Electronics'),
('Google Pixel 8 Pro',         'Google Tensor G3, 50MP camera, 7 years of updates',   49999, 20, 'Electronics'),
('OnePlus 12',                 'Snapdragon 8 Gen 3, 100W charging, Hasselblad camera',39999, 20, 'Electronics'),
('Xiaomi 14 Pro',              '1-inch Leica camera, 90W HyperCharge',                42999, 20, 'Electronics'),
('Apple MacBook Pro 16',       'M3 Max chip, 36GB RAM, Liquid Retina XDR display',    124999, 20, 'Electronics'),
('Apple MacBook Air 15',       'M2 chip, 15.3-inch Liquid Retina display, 18h battery',64999, 20, 'Electronics'),
('Dell XPS 15',                'Intel Core i9, OLED display, NVIDIA RTX 4070',        89999, 20, 'Electronics'),
('Lenovo ThinkPad X1 Carbon',  'Intel Core i7, 14-inch IPS, 57Wh battery',            74999, 20, 'Electronics'),
('Asus ROG Zephyrus G14',      'AMD Ryzen 9, RTX 4090, 240Hz QHD display',            94999, 20, 'Electronics'),
('Microsoft Surface Laptop 5', '13.5-inch PixelSense, Intel Core i7, Windows 11',     69999, 20, 'Electronics'),
('Apple iPad Pro 12.9',        'M2 chip, Liquid Retina XDR, Face ID, Thunderbolt',    49999, 20, 'Electronics'),
('Samsung Galaxy Tab S9 Ultra','14.6-inch Dynamic AMOLED 2X, Snapdragon 8 Gen 2',     54999, 20, 'Electronics'),
('Sony WH-1000XM5',            'Industry-leading noise cancellation, 30h battery',    14999, 20, 'Electronics'),
('Apple AirPods Pro 2',        'Active Noise Cancellation, Adaptive Audio, USB-C',    12999, 20, 'Electronics'),
('Bose QuietComfort 45',       'World-class noise cancellation, 24h battery',         11999, 20, 'Electronics'),
('Sony WF-1000XM5',            'True wireless earbuds, 8h + 16h battery, LDAC',       9999,  20, 'Electronics'),
('Jabra Evolve2 85',           'Professional headset, ANC, 37h battery',              13499, 20, 'Electronics'),
('Samsung 65" QLED 4K TV',     'Neo QLED 4K, 120Hz, HDR2000, Smart TV',              69999, 20, 'Electronics'),
('LG 55" OLED evo TV',         'Self-lit OLED pixels, α9 Gen6 AI processor',          64999, 20, 'Electronics'),
('Sony Bravia 77" A95L',       'QD-OLED 4K, XR Triluminos Max, 120Hz',               119999, 20, 'Electronics'),
('Canon EOS R5',               '45MP full-frame mirrorless, 8K RAW video',            109999, 20, 'Electronics'),
('Sony Alpha 7 IV',            '33MP full-frame, 4K 60fps, real-time tracking',       99999, 20, 'Electronics'),
('DJI Mini 4 Pro',             '4K/60fps drone, 34-min flight time, obstacle sensing',34999, 20, 'Electronics'),
('GoPro HERO12 Black',         '5.3K video, HyperSmooth 6.0, Max Lens Mod 2.0',      13999, 20, 'Electronics'),
('Apple Watch Ultra 2',        '49mm titanium, dual-frequency GPS, 60h battery',      39999, 20, 'Electronics'),
('Samsung Galaxy Watch 6 Classic','47mm, rotating bezel, BioActive Sensor, 40h',     17999, 20, 'Electronics'),
('Garmin Fenix 7X Solar',      'Solar charging, multi-GNSS, 28-day battery',          44999, 20, 'Electronics'),
-- Clothing
('Nike Air Force 1 Low',       'Iconic leather upper, cushioned Nike Air sole',        4999,  20, 'Clothing'),
('Adidas Ultraboost 23',       'Primeknit+ upper, BOOST midsole, Continental rubber', 6999,  20, 'Clothing'),
('New Balance 574',            'Suede and mesh upper, ENCAP midsole technology',       4499,  20, 'Clothing'),
('Puma RS-X',                  'Chunky retro silhouette, RS foam cushioning',          3999,  20, 'Clothing'),
('Converse Chuck Taylor All Star','Canvas upper, rubber sole, OrthoLite insole',      2999,  20, 'Clothing'),
('Vans Old Skool',             'Suede and canvas, waffle outsole, padded collar',      2799,  20, 'Clothing'),
('Levi\'s 501 Original Jeans', 'Straight fit, button fly, rigid denim',               2499,  20, 'Clothing'),
('Levi\'s 512 Slim Taper',     'Slim through hip and thigh, tapers below knee',        2699,  20, 'Clothing'),
('The North Face Nuptse Jacket','700-fill down, water-repellent, zip pockets',        8999,  20, 'Clothing'),
('Patagonia Nano Puff Jacket', 'PrimaLoft Gold Insulation, windproof shell',          7499,  20, 'Clothing'),
('Columbia Fleece Jacket',     'Polartec Classic 200, zippered hand pockets',         3999,  20, 'Clothing'),
('Uniqlo Ultra Light Down',    '90% down fill, packable to its own pocket',            2999,  20, 'Clothing'),
('Ralph Lauren Polo Shirt',    'Soft cotton mesh, embroidered pony logo',              1999,  20, 'Clothing'),
('Tommy Hilfiger Crew T-Shirt','100% cotton, signature striped logo',                  1499,  20, 'Clothing'),
('Champion Reverse Weave Hoodie','Heavyweight fleece, kangaroo pocket, ribbed cuffs', 3499,  20, 'Clothing'),
('Calvin Klein Boxer Briefs',  '3-pack, microfiber waistband, ergonomic pouch',       1299,  20, 'Clothing'),
('Nike Dri-FIT Running Shorts','Lightweight, 5-inch inseam, built-in liner',          1799,  20, 'Clothing'),
('Adidas Tiro Track Pants',    'Tricot fabric, side pockets, tapered fit',             1999,  20, 'Clothing'),
('Ray-Ban Wayfarer Sunglasses','Acetate frame, polarised G-15 lenses, UV400',         3999,  20, 'Clothing'),
('Casio G-Shock GA-2100',      'Carbon Core Guard, Shock Resistant, 200m WR',         4499,  20, 'Clothing'),
-- Home & Kitchen
('Dyson V15 Detect Absolute',  'Laser dust detection, HEPA filtration, 60-min run',   24999, 20, 'Home'),
('Roomba j7+',                 'Self-emptying, PrecisionVision Navigation, Wi-Fi',    29999, 20, 'Home'),
('KitchenAid Stand Mixer 5qt', 'Tilt-head, 10 speeds, 59-point planetary mixing',     14999, 20, 'Home'),
('Nespresso Vertuo Next',      'Centrifusion technology, 5 cup sizes, Wi-Fi capable', 6999,  20, 'Home'),
('De\'Longhi Magnifica Evo',   'Bean-to-cup, LatteCrema system, touchscreen',         19999, 20, 'Home'),
('Instant Pot Duo 7-in-1',     'Pressure cooker, slow cooker, rice cooker and more',  3999,  20, 'Home'),
('Philips Airfryer XXL',       '7.3L capacity, fat removal technology, keep warm',    5999,  20, 'Home'),
('Braun Series 9 Pro Shaver',  'SyncroSonic technology, 5 shaving elements',          8999,  20, 'Home'),
('Oral-B iO Series 9',         'AI-powered brushing, 7 modes, pressure sensor',       5999,  20, 'Home'),
('Dyson Purifier Hot+Cool',    'HEPA H13, heating, cooling and air purification',     21999, 20, 'Home'),
('IKEA KALLAX Shelf Unit',     '4x4 shelf unit, 147x147cm, white, versatile storage', 4999, 20, 'Home'),
('IKEA MALM Bed Frame',        'Queen size, high gloss white, 4 storage boxes',       6999,  20, 'Home'),
('Philips Hue Starter Kit',    '3x A21 smart bulbs + Bridge, 16M colors, app control',4999, 20, 'Home'),
('LIFX A60 Smart Bulb 3-pack', 'Wi-Fi, no hub required, 1100lm, 16M colors',          2999,  20, 'Home'),
('Levoit Core 300 Air Purifier','H13 True HEPA, covers 219 sq ft, ultra-quiet',       3499,  20, 'Home'),
-- Books
('Clean Code',                 'Robert C. Martin — A Handbook of Agile Software Craftsmanship', 999, 20, 'Books'),
('The Pragmatic Programmer',   'David Thomas & Andrew Hunt — Your Journey to Mastery', 999, 20, 'Books'),
('Design Patterns',            'Gang of Four — Elements of Reusable OO Software',      999,  20, 'Books'),
('System Design Interview',    'Alex Xu — An Insider\'s Guide, Volume 1',              999,  20, 'Books'),
('Spring Boot in Action',      'Craig Walls — Simplifying Spring application development', 899, 20, 'Books'),
('Java: The Complete Reference','Herbert Schildt — Covers Java SE 17',                899,  20, 'Books'),
('Effective Java 3rd Edition', 'Joshua Bloch — Best practices for Java platform',     999,  20, 'Books'),
('Database Internals',         'Alex Petrov — A Deep Dive into Distributed Systems',  1199, 20, 'Books'),
('Designing Data-Intensive Apps','Martin Kleppmann — Reliable, scalable, maintainable',1299, 20, 'Books'),
('The Docker Book',            'James Turnbull — Containerization with Docker',        899,  20, 'Books'),
('Atomic Habits',              'James Clear — An Easy & Proven Way to Build Habits',   599,  20, 'Books'),
('Deep Work',                  'Cal Newport — Rules for Focused Success in a Distracted World', 499, 20, 'Books'),
('Sapiens',                    'Yuval Noah Harari — A Brief History of Humankind',     599,  20, 'Books'),
('The Psychology of Money',    'Morgan Housel — Timeless lessons on wealth and greed', 549, 20, 'Books'),
('Zero to One',                'Peter Thiel — Notes on Startups, or How to Build the Future', 499, 20, 'Books'),
-- Sports & Outdoors
('Garmin Edge 840 Solar',      'Cycling GPS, ClimbPro, solar charging, mapping',       24999, 20, 'Sports'),
('Polar Vantage V3',           'Multisport GPS watch, AMOLED, ECG, running power',    37999, 20, 'Sports'),
('Wahoo KICKR Smart Trainer',  'Direct drive, WiFi, 2200W resistance, ERG mode',      34999, 20, 'Sports'),
('Theragun Pro Gen 6',         'Percussive therapy device, 6 attachments, OLED screen',14999, 20, 'Sports'),
('Fitbit Charge 6',            'GPS, 24/7 heart rate, stress management, 7-day battery',7999, 20, 'Sports'),
('Wilson Pro Staff RF 97',     'Roger Federer signature racket, 97sq.in head size',    8999,  20, 'Sports'),
('Yonex Astrox 100 ZZ',        'Badminton racket, graphite shaft, rotational generator', 6999, 20, 'Sports'),
('Adidas Predator Elite FG',   'Football boots, Controlframe outsole, Controllskin',  7999,  20, 'Sports'),
('Decathlon Domyos Yoga Mat',  '5mm thick, anti-slip, carrying strap included',        999,  20, 'Sports'),
('Bowflex SelectTech 552',     'Adjustable dumbbells 2-24kg, 15 weight settings',     19999, 20, 'Sports'),
-- Beauty & Health
('La Roche-Posay SPF 50+',     'Anthelios Invisible Fluid sunscreen, UVA/UVB protection', 699, 20, 'Beauty'),
('CeraVe Moisturising Cream',  '250ml, ceramides and hyaluronic acid, fragrance-free', 499, 20, 'Beauty'),
('The Ordinary Niacinamide',   '10% Niacinamide + 1% Zinc, pore minimising serum',    399,  20, 'Beauty'),
('Dyson Supersonic Hair Dryer','Intelligent heat control, magnetic attachments, fast dry',19999, 20, 'Beauty'),
('GHD Gold Professional Styler','Ceramic floating plates, 185°C optimum styling temp', 7999, 20, 'Beauty'),
('Philips Lumea IPL Series 9000','Hair removal, SmartSkin sensor, cordless use',      14999, 20, 'Beauty'),
-- Toys & Gaming
('PlayStation 5 Slim',         'PS5 console, 1TB SSD, DualSense controller, 4K',     19999, 20, 'Gaming'),
('Xbox Series X',              '12 teraflops GPU, 1TB SSD, 4K 120fps, Quick Resume',  19999, 20, 'Gaming'),
('Nintendo Switch OLED',       '7-inch OLED screen, enhanced audio, 64GB storage',    13999, 20, 'Gaming'),
('DualSense Edge Wireless',    'Ultra-customisable PS5 controller, swappable parts',   6999,  20, 'Gaming'),
('Logitech G Pro X Superlight 2','Wireless gaming mouse, HERO 25K sensor, 95g',       7999, 20, 'Gaming'),
('Razer BlackWidow V4 Pro',    'Mechanical gaming keyboard, Razer Green switches, RGB', 8999, 20, 'Gaming'),
('LEGO Technic Ferrari Daytona','42143, 3778 pieces, V12 engine functions',           7999,  20, 'Gaming'),
('Hasbro Monopoly Classic',    'Classic board game, 2-8 players, ages 8+',             999,  20, 'Gaming');
